#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACSN.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DACSN")]
	public partial class dbDACSNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbDACSNDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DACSNConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDACSNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDACSNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDACSNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDACSNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaNhiemCaNuoc> CaNhiemCaNuocs
		{
			get
			{
				return this.GetTable<CaNhiemCaNuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaNhiemCaNuoc")]
	public partial class CaNhiemCaNuoc
	{
		
		private System.Nullable<int> _SoCaNhiem;
		
		private System.Nullable<int> _DangDieuTri;
		
		private System.Nullable<int> _Khoi;
		
		private System.Nullable<int> _TuVong;
		
		public CaNhiemCaNuoc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCaNhiem", DbType="Int")]
		public System.Nullable<int> SoCaNhiem
		{
			get
			{
				return this._SoCaNhiem;
			}
			set
			{
				if ((this._SoCaNhiem != value))
				{
					this._SoCaNhiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangDieuTri", DbType="Int")]
		public System.Nullable<int> DangDieuTri
		{
			get
			{
				return this._DangDieuTri;
			}
			set
			{
				if ((this._DangDieuTri != value))
				{
					this._DangDieuTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoi", DbType="Int")]
		public System.Nullable<int> Khoi
		{
			get
			{
				return this._Khoi;
			}
			set
			{
				if ((this._Khoi != value))
				{
					this._Khoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuVong", DbType="Int")]
		public System.Nullable<int> TuVong
		{
			get
			{
				return this._TuVong;
			}
			set
			{
				if ((this._TuVong != value))
				{
					this._TuVong = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
