#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACSN.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DuLieuYTe")]
	public partial class dbDuLieuYTeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBaiViet(BaiViet instance);
    partial void UpdateBaiViet(BaiViet instance);
    partial void DeleteBaiViet(BaiViet instance);
    partial void InsertChiDao(ChiDao instance);
    partial void UpdateChiDao(ChiDao instance);
    partial void DeleteChiDao(ChiDao instance);
    partial void InsertLoai_BaiViet(Loai_BaiViet instance);
    partial void UpdateLoai_BaiViet(Loai_BaiViet instance);
    partial void DeleteLoai_BaiViet(Loai_BaiViet instance);
    partial void InsertDuyetBaiViet(DuyetBaiViet instance);
    partial void UpdateDuyetBaiViet(DuyetBaiViet instance);
    partial void DeleteDuyetBaiViet(DuyetBaiViet instance);
    partial void InsertTag(Tag instance);
    partial void UpdateTag(Tag instance);
    partial void DeleteTag(Tag instance);
    partial void InsertTai_Khoan(Tai_Khoan instance);
    partial void UpdateTai_Khoan(Tai_Khoan instance);
    partial void DeleteTai_Khoan(Tai_Khoan instance);
    partial void InsertThongTin_KhaiBao(ThongTin_KhaiBao instance);
    partial void UpdateThongTin_KhaiBao(ThongTin_KhaiBao instance);
    partial void DeleteThongTin_KhaiBao(ThongTin_KhaiBao instance);
    partial void InsertThongTinTaiKhoan(ThongTinTaiKhoan instance);
    partial void UpdateThongTinTaiKhoan(ThongTinTaiKhoan instance);
    partial void DeleteThongTinTaiKhoan(ThongTinTaiKhoan instance);
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    partial void InsertVaccine(Vaccine instance);
    partial void UpdateVaccine(Vaccine instance);
    partial void DeleteVaccine(Vaccine instance);
    partial void InsertVideo(Video instance);
    partial void UpdateVideo(Video instance);
    partial void DeleteVideo(Video instance);
    #endregion
		
		public dbDuLieuYTeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DuLieuYTeConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDuLieuYTeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDuLieuYTeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDuLieuYTeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDuLieuYTeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BaiViet> BaiViets
		{
			get
			{
				return this.GetTable<BaiViet>();
			}
		}
		
		public System.Data.Linq.Table<ChiDao> ChiDaos
		{
			get
			{
				return this.GetTable<ChiDao>();
			}
		}
		
		public System.Data.Linq.Table<Loai_BaiViet> Loai_BaiViets
		{
			get
			{
				return this.GetTable<Loai_BaiViet>();
			}
		}
		
		public System.Data.Linq.Table<DuyetBaiViet> DuyetBaiViets
		{
			get
			{
				return this.GetTable<DuyetBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<Tag> Tags
		{
			get
			{
				return this.GetTable<Tag>();
			}
		}
		
		public System.Data.Linq.Table<Tai_Khoan> Tai_Khoans
		{
			get
			{
				return this.GetTable<Tai_Khoan>();
			}
		}
		
		public System.Data.Linq.Table<ThongTin_KhaiBao> ThongTin_KhaiBaos
		{
			get
			{
				return this.GetTable<ThongTin_KhaiBao>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinTaiKhoan> ThongTinTaiKhoans
		{
			get
			{
				return this.GetTable<ThongTinTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<Vaccine> Vaccines
		{
			get
			{
				return this.GetTable<Vaccine>();
			}
		}
		
		public System.Data.Linq.Table<Video> Videos
		{
			get
			{
				return this.GetTable<Video>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiViet")]
	public partial class BaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdBaiViet;
		
		private string _IdLoai;
		
		private string _TieuDe;
		
		private string _TomTat;
		
		private string _NoiDung;
		
		private System.DateTime _NgayViet;
		
		private string _Anh;
		
		private System.Nullable<int> _LuotTruyCap;
		
		private string _IdTag;
		
		private string _NguoiViet;
		
		private EntityRef<DuyetBaiViet> _DuyetBaiViet;
		
		private EntityRef<Loai_BaiViet> _Loai_BaiViet;
		
		private EntityRef<Tag> _Tag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBaiVietChanging(string value);
    partial void OnIdBaiVietChanged();
    partial void OnIdLoaiChanging(string value);
    partial void OnIdLoaiChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTomTatChanging(string value);
    partial void OnTomTatChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayVietChanging(System.DateTime value);
    partial void OnNgayVietChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnLuotTruyCapChanging(System.Nullable<int> value);
    partial void OnLuotTruyCapChanged();
    partial void OnIdTagChanging(string value);
    partial void OnIdTagChanged();
    partial void OnNguoiVietChanging(string value);
    partial void OnNguoiVietChanged();
    #endregion
		
		public BaiViet()
		{
			this._DuyetBaiViet = default(EntityRef<DuyetBaiViet>);
			this._Loai_BaiViet = default(EntityRef<Loai_BaiViet>);
			this._Tag = default(EntityRef<Tag>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBaiViet", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdBaiViet
		{
			get
			{
				return this._IdBaiViet;
			}
			set
			{
				if ((this._IdBaiViet != value))
				{
					this.OnIdBaiVietChanging(value);
					this.SendPropertyChanging();
					this._IdBaiViet = value;
					this.SendPropertyChanged("IdBaiViet");
					this.OnIdBaiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoai", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdLoai
		{
			get
			{
				return this._IdLoai;
			}
			set
			{
				if ((this._IdLoai != value))
				{
					if (this._Loai_BaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLoaiChanging(value);
					this.SendPropertyChanging();
					this._IdLoai = value;
					this.SendPropertyChanged("IdLoai");
					this.OnIdLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TomTat
		{
			get
			{
				return this._TomTat;
			}
			set
			{
				if ((this._TomTat != value))
				{
					this.OnTomTatChanging(value);
					this.SendPropertyChanging();
					this._TomTat = value;
					this.SendPropertyChanged("TomTat");
					this.OnTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayViet", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayViet
		{
			get
			{
				return this._NgayViet;
			}
			set
			{
				if ((this._NgayViet != value))
				{
					this.OnNgayVietChanging(value);
					this.SendPropertyChanging();
					this._NgayViet = value;
					this.SendPropertyChanged("NgayViet");
					this.OnNgayVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotTruyCap", DbType="Int")]
		public System.Nullable<int> LuotTruyCap
		{
			get
			{
				return this._LuotTruyCap;
			}
			set
			{
				if ((this._LuotTruyCap != value))
				{
					this.OnLuotTruyCapChanging(value);
					this.SendPropertyChanging();
					this._LuotTruyCap = value;
					this.SendPropertyChanged("LuotTruyCap");
					this.OnLuotTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTag", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdTag
		{
			get
			{
				return this._IdTag;
			}
			set
			{
				if ((this._IdTag != value))
				{
					if (this._Tag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTagChanging(value);
					this.SendPropertyChanging();
					this._IdTag = value;
					this.SendPropertyChanged("IdTag");
					this.OnIdTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiViet", DbType="NVarChar(50)")]
		public string NguoiViet
		{
			get
			{
				return this._NguoiViet;
			}
			set
			{
				if ((this._NguoiViet != value))
				{
					this.OnNguoiVietChanging(value);
					this.SendPropertyChanging();
					this._NguoiViet = value;
					this.SendPropertyChanged("NguoiViet");
					this.OnNguoiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_DuyetBaiViet", Storage="_DuyetBaiViet", ThisKey="IdBaiViet", OtherKey="IdBaiViet", IsUnique=true, IsForeignKey=false)]
		public DuyetBaiViet DuyetBaiViet
		{
			get
			{
				return this._DuyetBaiViet.Entity;
			}
			set
			{
				DuyetBaiViet previousValue = this._DuyetBaiViet.Entity;
				if (((previousValue != value) 
							|| (this._DuyetBaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuyetBaiViet.Entity = null;
						previousValue.BaiViet = null;
					}
					this._DuyetBaiViet.Entity = value;
					if ((value != null))
					{
						value.BaiViet = this;
					}
					this.SendPropertyChanged("DuyetBaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_BaiViet_BaiViet", Storage="_Loai_BaiViet", ThisKey="IdLoai", OtherKey="IdLoai", IsForeignKey=true)]
		public Loai_BaiViet Loai_BaiViet
		{
			get
			{
				return this._Loai_BaiViet.Entity;
			}
			set
			{
				Loai_BaiViet previousValue = this._Loai_BaiViet.Entity;
				if (((previousValue != value) 
							|| (this._Loai_BaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loai_BaiViet.Entity = null;
						previousValue.BaiViets.Remove(this);
					}
					this._Loai_BaiViet.Entity = value;
					if ((value != null))
					{
						value.BaiViets.Add(this);
						this._IdLoai = value.IdLoai;
					}
					else
					{
						this._IdLoai = default(string);
					}
					this.SendPropertyChanged("Loai_BaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tag_BaiViet", Storage="_Tag", ThisKey="IdTag", OtherKey="IdTag", IsForeignKey=true)]
		public Tag Tag
		{
			get
			{
				return this._Tag.Entity;
			}
			set
			{
				Tag previousValue = this._Tag.Entity;
				if (((previousValue != value) 
							|| (this._Tag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tag.Entity = null;
						previousValue.BaiViets.Remove(this);
					}
					this._Tag.Entity = value;
					if ((value != null))
					{
						value.BaiViets.Add(this);
						this._IdTag = value.IdTag;
					}
					else
					{
						this._IdTag = default(string);
					}
					this.SendPropertyChanged("Tag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiDao")]
	public partial class ChiDao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDChiDao;
		
		private string _TieuDeChiDao;
		
		private string _NoiDungChiDao;
		
		private System.DateTime _NgayViet;
		
		private string _AnhChiDao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChiDaoChanging(int value);
    partial void OnIDChiDaoChanged();
    partial void OnTieuDeChiDaoChanging(string value);
    partial void OnTieuDeChiDaoChanged();
    partial void OnNoiDungChiDaoChanging(string value);
    partial void OnNoiDungChiDaoChanged();
    partial void OnNgayVietChanging(System.DateTime value);
    partial void OnNgayVietChanged();
    partial void OnAnhChiDaoChanging(string value);
    partial void OnAnhChiDaoChanged();
    #endregion
		
		public ChiDao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiDao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDChiDao
		{
			get
			{
				return this._IDChiDao;
			}
			set
			{
				if ((this._IDChiDao != value))
				{
					this.OnIDChiDaoChanging(value);
					this.SendPropertyChanging();
					this._IDChiDao = value;
					this.SendPropertyChanged("IDChiDao");
					this.OnIDChiDaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDeChiDao", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TieuDeChiDao
		{
			get
			{
				return this._TieuDeChiDao;
			}
			set
			{
				if ((this._TieuDeChiDao != value))
				{
					this.OnTieuDeChiDaoChanging(value);
					this.SendPropertyChanging();
					this._TieuDeChiDao = value;
					this.SendPropertyChanged("TieuDeChiDao");
					this.OnTieuDeChiDaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungChiDao", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungChiDao
		{
			get
			{
				return this._NoiDungChiDao;
			}
			set
			{
				if ((this._NoiDungChiDao != value))
				{
					this.OnNoiDungChiDaoChanging(value);
					this.SendPropertyChanging();
					this._NoiDungChiDao = value;
					this.SendPropertyChanged("NoiDungChiDao");
					this.OnNoiDungChiDaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayViet", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayViet
		{
			get
			{
				return this._NgayViet;
			}
			set
			{
				if ((this._NgayViet != value))
				{
					this.OnNgayVietChanging(value);
					this.SendPropertyChanging();
					this._NgayViet = value;
					this.SendPropertyChanged("NgayViet");
					this.OnNgayVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhChiDao", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string AnhChiDao
		{
			get
			{
				return this._AnhChiDao;
			}
			set
			{
				if ((this._AnhChiDao != value))
				{
					this.OnAnhChiDaoChanging(value);
					this.SendPropertyChanging();
					this._AnhChiDao = value;
					this.SendPropertyChanged("AnhChiDao");
					this.OnAnhChiDaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loai_BaiViet")]
	public partial class Loai_BaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdLoai;
		
		private string _TenLoai;
		
		private EntitySet<BaiViet> _BaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLoaiChanging(string value);
    partial void OnIdLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public Loai_BaiViet()
		{
			this._BaiViets = new EntitySet<BaiViet>(new Action<BaiViet>(this.attach_BaiViets), new Action<BaiViet>(this.detach_BaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLoai", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdLoai
		{
			get
			{
				return this._IdLoai;
			}
			set
			{
				if ((this._IdLoai != value))
				{
					this.OnIdLoaiChanging(value);
					this.SendPropertyChanging();
					this._IdLoai = value;
					this.SendPropertyChanged("IdLoai");
					this.OnIdLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_BaiViet_BaiViet", Storage="_BaiViets", ThisKey="IdLoai", OtherKey="IdLoai")]
		public EntitySet<BaiViet> BaiViets
		{
			get
			{
				return this._BaiViets;
			}
			set
			{
				this._BaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.Loai_BaiViet = this;
		}
		
		private void detach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.Loai_BaiViet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuyetBaiViet")]
	public partial class DuyetBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdBaiViet;
		
		private System.Nullable<bool> _TinhTrang;
		
		private int _Nguoiduyet;
		
		private System.DateTime _NgayDuyet;
		
		private EntityRef<BaiViet> _BaiViet;
		
		private EntityRef<ThongTinTaiKhoan> _ThongTinTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBaiVietChanging(string value);
    partial void OnIdBaiVietChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnNguoiduyetChanging(int value);
    partial void OnNguoiduyetChanged();
    partial void OnNgayDuyetChanging(System.DateTime value);
    partial void OnNgayDuyetChanged();
    #endregion
		
		public DuyetBaiViet()
		{
			this._BaiViet = default(EntityRef<BaiViet>);
			this._ThongTinTaiKhoan = default(EntityRef<ThongTinTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBaiViet", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdBaiViet
		{
			get
			{
				return this._IdBaiViet;
			}
			set
			{
				if ((this._IdBaiViet != value))
				{
					if (this._BaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdBaiVietChanging(value);
					this.SendPropertyChanging();
					this._IdBaiViet = value;
					this.SendPropertyChanged("IdBaiViet");
					this.OnIdBaiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoiduyet", DbType="Int NOT NULL")]
		public int Nguoiduyet
		{
			get
			{
				return this._Nguoiduyet;
			}
			set
			{
				if ((this._Nguoiduyet != value))
				{
					if (this._ThongTinTaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiduyetChanging(value);
					this.SendPropertyChanging();
					this._Nguoiduyet = value;
					this.SendPropertyChanged("Nguoiduyet");
					this.OnNguoiduyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyet", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgayDuyet
		{
			get
			{
				return this._NgayDuyet;
			}
			set
			{
				if ((this._NgayDuyet != value))
				{
					this.OnNgayDuyetChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyet = value;
					this.SendPropertyChanged("NgayDuyet");
					this.OnNgayDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_DuyetBaiViet", Storage="_BaiViet", ThisKey="IdBaiViet", OtherKey="IdBaiViet", IsForeignKey=true)]
		public BaiViet BaiViet
		{
			get
			{
				return this._BaiViet.Entity;
			}
			set
			{
				BaiViet previousValue = this._BaiViet.Entity;
				if (((previousValue != value) 
							|| (this._BaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BaiViet.Entity = null;
						previousValue.DuyetBaiViet = null;
					}
					this._BaiViet.Entity = value;
					if ((value != null))
					{
						value.DuyetBaiViet = this;
						this._IdBaiViet = value.IdBaiViet;
					}
					else
					{
						this._IdBaiViet = default(string);
					}
					this.SendPropertyChanged("BaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinTaiKhoan_DuyetBaiViet", Storage="_ThongTinTaiKhoan", ThisKey="Nguoiduyet", OtherKey="IdTaiKhoan", IsForeignKey=true)]
		public ThongTinTaiKhoan ThongTinTaiKhoan
		{
			get
			{
				return this._ThongTinTaiKhoan.Entity;
			}
			set
			{
				ThongTinTaiKhoan previousValue = this._ThongTinTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._ThongTinTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTinTaiKhoan.Entity = null;
						previousValue.DuyetBaiViets.Remove(this);
					}
					this._ThongTinTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.DuyetBaiViets.Add(this);
						this._Nguoiduyet = value.IdTaiKhoan;
					}
					else
					{
						this._Nguoiduyet = default(int);
					}
					this.SendPropertyChanged("ThongTinTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tag")]
	public partial class Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTag;
		
		private string _TenTag;
		
		private EntitySet<BaiViet> _BaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTagChanging(string value);
    partial void OnIdTagChanged();
    partial void OnTenTagChanging(string value);
    partial void OnTenTagChanged();
    #endregion
		
		public Tag()
		{
			this._BaiViets = new EntitySet<BaiViet>(new Action<BaiViet>(this.attach_BaiViets), new Action<BaiViet>(this.detach_BaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTag", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTag
		{
			get
			{
				return this._IdTag;
			}
			set
			{
				if ((this._IdTag != value))
				{
					this.OnIdTagChanging(value);
					this.SendPropertyChanging();
					this._IdTag = value;
					this.SendPropertyChanged("IdTag");
					this.OnIdTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTag", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenTag
		{
			get
			{
				return this._TenTag;
			}
			set
			{
				if ((this._TenTag != value))
				{
					this.OnTenTagChanging(value);
					this.SendPropertyChanging();
					this._TenTag = value;
					this.SendPropertyChanged("TenTag");
					this.OnTenTagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tag_BaiViet", Storage="_BaiViets", ThisKey="IdTag", OtherKey="IdTag")]
		public EntitySet<BaiViet> BaiViets
		{
			get
			{
				return this._BaiViets;
			}
			set
			{
				this._BaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.Tag = this;
		}
		
		private void detach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.Tag = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tai_Khoan")]
	public partial class Tai_Khoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTaiKhoan;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private EntityRef<ThongTinTaiKhoan> _ThongTinTaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(int value);
    partial void OnIdTaiKhoanChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public Tai_Khoan()
		{
			this._ThongTinTaiKhoan = default(EntityRef<ThongTinTaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_ThongTinTaiKhoan", Storage="_ThongTinTaiKhoan", ThisKey="IdTaiKhoan", OtherKey="IdTaiKhoan", IsUnique=true, IsForeignKey=false)]
		public ThongTinTaiKhoan ThongTinTaiKhoan
		{
			get
			{
				return this._ThongTinTaiKhoan.Entity;
			}
			set
			{
				ThongTinTaiKhoan previousValue = this._ThongTinTaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._ThongTinTaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTinTaiKhoan.Entity = null;
						previousValue.Tai_Khoan = null;
					}
					this._ThongTinTaiKhoan.Entity = value;
					if ((value != null))
					{
						value.Tai_Khoan = this;
					}
					this.SendPropertyChanged("ThongTinTaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTin_KhaiBao")]
	public partial class ThongTin_KhaiBao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HoVaTen;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _TinhTrang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHoVaTenChanging(string value);
    partial void OnHoVaTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public ThongTin_KhaiBao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this.OnHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._HoVaTen = value;
					this.SendPropertyChanged("HoVaTen");
					this.OnHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinTaiKhoan")]
	public partial class ThongTinTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTaiKhoan;
		
		private string _HovaTen;
		
		private System.DateTime _NgaySinh;
		
		private string _SoDienThoai;
		
		private string _Gmail;
		
		private string _DiaChi;
		
		private string _ChucVu;
		
		private EntitySet<DuyetBaiViet> _DuyetBaiViets;
		
		private EntityRef<Tai_Khoan> _Tai_Khoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTaiKhoanChanging(int value);
    partial void OnIdTaiKhoanChanged();
    partial void OnHovaTenChanging(string value);
    partial void OnHovaTenChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnGmailChanging(string value);
    partial void OnGmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public ThongTinTaiKhoan()
		{
			this._DuyetBaiViets = new EntitySet<DuyetBaiViet>(new Action<DuyetBaiViet>(this.attach_DuyetBaiViets), new Action<DuyetBaiViet>(this.detach_DuyetBaiViets));
			this._Tai_Khoan = default(EntityRef<Tai_Khoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTaiKhoan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdTaiKhoan
		{
			get
			{
				return this._IdTaiKhoan;
			}
			set
			{
				if ((this._IdTaiKhoan != value))
				{
					if (this._Tai_Khoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IdTaiKhoan = value;
					this.SendPropertyChanged("IdTaiKhoan");
					this.OnIdTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HovaTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HovaTen
		{
			get
			{
				return this._HovaTen;
			}
			set
			{
				if ((this._HovaTen != value))
				{
					this.OnHovaTenChanging(value);
					this.SendPropertyChanging();
					this._HovaTen = value;
					this.SendPropertyChanged("HovaTen");
					this.OnHovaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gmail", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Gmail
		{
			get
			{
				return this._Gmail;
			}
			set
			{
				if ((this._Gmail != value))
				{
					this.OnGmailChanging(value);
					this.SendPropertyChanging();
					this._Gmail = value;
					this.SendPropertyChanged("Gmail");
					this.OnGmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinTaiKhoan_DuyetBaiViet", Storage="_DuyetBaiViets", ThisKey="IdTaiKhoan", OtherKey="Nguoiduyet")]
		public EntitySet<DuyetBaiViet> DuyetBaiViets
		{
			get
			{
				return this._DuyetBaiViets;
			}
			set
			{
				this._DuyetBaiViets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_ThongTinTaiKhoan", Storage="_Tai_Khoan", ThisKey="IdTaiKhoan", OtherKey="IdTaiKhoan", IsForeignKey=true)]
		public Tai_Khoan Tai_Khoan
		{
			get
			{
				return this._Tai_Khoan.Entity;
			}
			set
			{
				Tai_Khoan previousValue = this._Tai_Khoan.Entity;
				if (((previousValue != value) 
							|| (this._Tai_Khoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tai_Khoan.Entity = null;
						previousValue.ThongTinTaiKhoan = null;
					}
					this._Tai_Khoan.Entity = value;
					if ((value != null))
					{
						value.ThongTinTaiKhoan = this;
						this._IdTaiKhoan = value.IdTaiKhoan;
					}
					else
					{
						this._IdTaiKhoan = default(int);
					}
					this.SendPropertyChanged("Tai_Khoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuyetBaiViets(DuyetBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinTaiKhoan = this;
		}
		
		private void detach_DuyetBaiViets(DuyetBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinTaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTinTuc;
		
		private string _TieuDe;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _NoiDung;
		
		private string _AnhBia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTinTucChanging(int value);
    partial void OnIdTinTucChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    #endregion
		
		public TinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTinTuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTinTuc
		{
			get
			{
				return this._IdTinTuc;
			}
			set
			{
				if ((this._IdTinTuc != value))
				{
					this.OnIdTinTucChanging(value);
					this.SendPropertyChanging();
					this._IdTinTuc = value;
					this.SendPropertyChanged("IdTinTuc");
					this.OnIdTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(50)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vaccine")]
	public partial class Vaccine : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Idvaccine;
		
		private string _TenChuDeVaccine;
		
		private string _AnhCD;
		
		private string _NoiDungCD;
		
		private System.Nullable<System.DateTime> _NgayCapNhatCD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdvaccineChanging(int value);
    partial void OnIdvaccineChanged();
    partial void OnTenChuDeVaccineChanging(string value);
    partial void OnTenChuDeVaccineChanged();
    partial void OnAnhCDChanging(string value);
    partial void OnAnhCDChanged();
    partial void OnNoiDungCDChanging(string value);
    partial void OnNoiDungCDChanged();
    partial void OnNgayCapNhatCDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatCDChanged();
    #endregion
		
		public Vaccine()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idvaccine", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Idvaccine
		{
			get
			{
				return this._Idvaccine;
			}
			set
			{
				if ((this._Idvaccine != value))
				{
					this.OnIdvaccineChanging(value);
					this.SendPropertyChanging();
					this._Idvaccine = value;
					this.SendPropertyChanged("Idvaccine");
					this.OnIdvaccineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuDeVaccine", DbType="NVarChar(200)")]
		public string TenChuDeVaccine
		{
			get
			{
				return this._TenChuDeVaccine;
			}
			set
			{
				if ((this._TenChuDeVaccine != value))
				{
					this.OnTenChuDeVaccineChanging(value);
					this.SendPropertyChanging();
					this._TenChuDeVaccine = value;
					this.SendPropertyChanged("TenChuDeVaccine");
					this.OnTenChuDeVaccineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhCD", DbType="NVarChar(200)")]
		public string AnhCD
		{
			get
			{
				return this._AnhCD;
			}
			set
			{
				if ((this._AnhCD != value))
				{
					this.OnAnhCDChanging(value);
					this.SendPropertyChanging();
					this._AnhCD = value;
					this.SendPropertyChanged("AnhCD");
					this.OnAnhCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCD", DbType="NVarChar(200)")]
		public string NoiDungCD
		{
			get
			{
				return this._NoiDungCD;
			}
			set
			{
				if ((this._NoiDungCD != value))
				{
					this.OnNoiDungCDChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCD = value;
					this.SendPropertyChanged("NoiDungCD");
					this.OnNoiDungCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhatCD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCapNhatCD
		{
			get
			{
				return this._NgayCapNhatCD;
			}
			set
			{
				if ((this._NgayCapNhatCD != value))
				{
					this.OnNgayCapNhatCDChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhatCD = value;
					this.SendPropertyChanged("NgayCapNhatCD");
					this.OnNgayCapNhatCDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Video")]
	public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVideo;
		
		private string _TenVideo;
		
		private string _Video1;
		
		private string _NoiDungVideo;
		
		private System.Nullable<System.DateTime> _NgayCapNhatVideo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVideoChanging(int value);
    partial void OnIdVideoChanged();
    partial void OnTenVideoChanging(string value);
    partial void OnTenVideoChanged();
    partial void OnVideo1Changing(string value);
    partial void OnVideo1Changed();
    partial void OnNoiDungVideoChanging(string value);
    partial void OnNoiDungVideoChanged();
    partial void OnNgayCapNhatVideoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatVideoChanged();
    #endregion
		
		public Video()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVideo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVideo
		{
			get
			{
				return this._IdVideo;
			}
			set
			{
				if ((this._IdVideo != value))
				{
					this.OnIdVideoChanging(value);
					this.SendPropertyChanging();
					this._IdVideo = value;
					this.SendPropertyChanged("IdVideo");
					this.OnIdVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVideo", DbType="NVarChar(200)")]
		public string TenVideo
		{
			get
			{
				return this._TenVideo;
			}
			set
			{
				if ((this._TenVideo != value))
				{
					this.OnTenVideoChanging(value);
					this.SendPropertyChanging();
					this._TenVideo = value;
					this.SendPropertyChanged("TenVideo");
					this.OnTenVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Video", Storage="_Video1", DbType="NVarChar(200)")]
		public string Video1
		{
			get
			{
				return this._Video1;
			}
			set
			{
				if ((this._Video1 != value))
				{
					this.OnVideo1Changing(value);
					this.SendPropertyChanging();
					this._Video1 = value;
					this.SendPropertyChanged("Video1");
					this.OnVideo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVideo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVideo
		{
			get
			{
				return this._NoiDungVideo;
			}
			set
			{
				if ((this._NoiDungVideo != value))
				{
					this.OnNoiDungVideoChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVideo = value;
					this.SendPropertyChanged("NoiDungVideo");
					this.OnNoiDungVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhatVideo", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCapNhatVideo
		{
			get
			{
				return this._NgayCapNhatVideo;
			}
			set
			{
				if ((this._NgayCapNhatVideo != value))
				{
					this.OnNgayCapNhatVideoChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhatVideo = value;
					this.SendPropertyChanged("NgayCapNhatVideo");
					this.OnNgayCapNhatVideoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
